//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CZAS_PRACY
    {
        public int CZA_ID { get; set; }
        public int PRA_ID { get; set; }
        public System.DateTime CZA_OD { get; set; }
        public System.DateTime CZA_DO { get; set; }
    
        public virtual PRACOWNICY PRACOWNICY { get; set; }
    }
}
