//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSTEPNE_NAGRODY
    {
        public DOSTEPNE_NAGRODY()
        {
            this.NAGRODY_KLIENCI = new HashSet<NAGRODY_KLIENCI>();
        }
    
        public int NAG_ID { get; set; }
        public string NAG_NAZWA { get; set; }
        public bool NAG_AKTYWNA { get; set; }
        public int NAG_PUNKTY { get; set; }
        public string NAG_SCIEZKA_OBRAZKA { get; set; }
    
        public virtual ICollection<NAGRODY_KLIENCI> NAGRODY_KLIENCI { get; set; }
    }
}
