//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLIENCI
    {
        public KLIENCI()
        {
            this.NAGRODY_KLIENCI = new HashSet<NAGRODY_KLIENCI>();
            this.REZERWACJE = new HashSet<REZERWACJE>();
        }
    
        public int KLI_ID { get; set; }
        public int OSO_ID { get; set; }
        public string KLI_EMAIL { get; set; }
        public int KLI_PUNKTY { get; set; }
        public bool KLI_ZABLOKOWANY { get; set; }
    
        public virtual OSOBY OSOBY { get; set; }
        public virtual ICollection<NAGRODY_KLIENCI> NAGRODY_KLIENCI { get; set; }
        public virtual ICollection<REZERWACJE> REZERWACJE { get; set; }
    }
}
