//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KURSY
    {
        public KURSY()
        {
            this.PRZEJAZDY = new HashSet<PRZEJAZDY>();
            this.TRASA = new HashSet<TRASA>();
        }
    
        public int KUR_ID { get; set; }
        public string KUR_RELACJA { get; set; }
        public string KUR_NAZWA { get; set; }
    
        public virtual ICollection<PRZEJAZDY> PRZEJAZDY { get; set; }
        public virtual ICollection<TRASA> TRASA { get; set; }
    }
}
