//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAGRODY_KLIENCI
    {
        public int NAK_ID { get; set; }
        public int KLI_ID { get; set; }
        public int NAG_ID { get; set; }
        public string NAK_ADRES_WYSYLKI { get; set; }
    
        public virtual DOSTEPNE_NAGRODY DOSTEPNE_NAGRODY { get; set; }
        public virtual KLIENCI KLIENCI { get; set; }
    }
}
