//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSOBY
    {
        public OSOBY()
        {
            this.KIEROWCY = new HashSet<KIEROWCY>();
            this.KLIENCI = new HashSet<KLIENCI>();
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
        }
    
        public int OSO_ID { get; set; }
        public string OSO_IMIE { get; set; }
        public string OSO_NAZWISKO { get; set; }
        public string OSO_PESEL { get; set; }
        public string OSO_TELEFON { get; set; }
        public System.DateTime OSO_DATA_URODZENIA { get; set; }
        public string OSO_LOGIN { get; set; }
        public string OSO_HASLO { get; set; }
    
        public virtual ICollection<KIEROWCY> KIEROWCY { get; set; }
        public virtual ICollection<KLIENCI> KLIENCI { get; set; }
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
    }
}
