//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POJAZDY
    {
        public POJAZDY()
        {
            this.TANKOWANIA = new HashSet<TANKOWANIA>();
        }
    
        public int POJ_ID { get; set; }
        public string POJ_MARKA { get; set; }
        public string POJ_SILNIK { get; set; }
        public System.DateTime POJ_DATA_PRODUKCJI { get; set; }
        public Nullable<System.DateTime> POJ_UBEZPIECZONY_DO { get; set; }
        public byte[] POJ_SPRAWNY { get; set; }
        public string POJ_ADNOTACJE { get; set; }
        public int POJ_MIEJSCA { get; set; }
    
        public virtual ICollection<TANKOWANIA> TANKOWANIA { get; set; }
    }
}
