//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNICY
    {
        public PRACOWNICY()
        {
            this.CZAS_PRACY = new HashSet<CZAS_PRACY>();
            this.PRZEJAZDY = new HashSet<PRZEJAZDY>();
        }
    
        public int PRA_ID { get; set; }
        public int OSO_ID { get; set; }
        public string PRA_UPRAWNIENIA { get; set; }
    
        public virtual ICollection<CZAS_PRACY> CZAS_PRACY { get; set; }
        public virtual OSOBY OSOBY { get; set; }
        public virtual ICollection<PRZEJAZDY> PRZEJAZDY { get; set; }
    }
}
