//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRZEJAZDY
    {
        public PRZEJAZDY()
        {
            this.REZERWACJE = new HashSet<REZERWACJE>();
        }
    
        public int PRZ_ID { get; set; }
        public int KUR_ID { get; set; }
        public int PRA_ID { get; set; }
        public int KIE_ID { get; set; }
        public bool PRZ_AKTYWNY { get; set; }
        public System.DateTime PRZ_ODJAZD { get; set; }
    
        public virtual KIEROWCY KIEROWCY { get; set; }
        public virtual KURSY KURSY { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual ICollection<REZERWACJE> REZERWACJE { get; set; }
    }
}
