//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RODZAJE_BILETOW
    {
        public RODZAJE_BILETOW()
        {
            this.ULGI_REZERWACJA = new HashSet<ULGI_REZERWACJA>();
        }
    
        public int ROD_ID { get; set; }
        public string ROD_NAZWA { get; set; }
        public int ROD_WIEK { get; set; }
        public int ROD_ZNIZKA { get; set; }
    
        public virtual ICollection<ULGI_REZERWACJA> ULGI_REZERWACJA { get; set; }
    }
}
