//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANKOWANIA
    {
        public int TAN_ID { get; set; }
        public int KIE_ID { get; set; }
        public int POJ_ID { get; set; }
        public double TAN_ILOSC { get; set; }
        public double TAN_KWOTA { get; set; }
        public System.DateTime TAN_NASTEPNE { get; set; }
        public int TAN_PRZEJECHANO { get; set; }
    
        public virtual KIEROWCY KIEROWCY { get; set; }
        public virtual POJAZDY POJAZDY { get; set; }
    }
}
