//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBusWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRASA
    {
        public int TRA_ID { get; set; }
        public int KUR_ID { get; set; }
        public int PRZY_ID { get; set; }
        public int TRA_KOLEJNOSC { get; set; }
        public int TRA_CZAS_PRZEJAZDU { get; set; }
        public double TRA_CENA { get; set; }
    
        public virtual KURSY KURSY { get; set; }
        public virtual PRZYSTANKI PRZYSTANKI { get; set; }
    }
}
